### ISSUE TITLE
Menção equivocada a um quarto objetivo do livro

### ISSUE THREAD

**Issue by lincolnfrias** [DjalmaPessoa/adac#11]
A [seção de obejtivos](https://djalmapessoa.github.io/adac/introduc.html#objetivos-do-livro) menciona três pontos mas faz referência a um quarto ponto:

> O ponto iv) não é tratado de forma completa neste texto.

Aproveitando, muito obrigado pelo excelente trabalho!

**Comment by DjalmaPessoa** [comment]
A referência é ao ponto iv)   (romano)  e não ao ponto 4).  O item iv) está na lista de aspectos relevantes no caso de amostras complexas, situada no início do capítulo:  

iv.)  **calibração ou imputação para não-resposta e outros ajustes**.

Não-resposta será, futuramente, objeto do capítulo 11.
